import * as THREE from 'three';
import {HOUSE,WALLS,FRONT_POLYGON,FIRST_POLYGON,SECOND_POLYGONS,HOLES,STAIRS,insidePolygon} from '../data/houseData.js';
import {box,group,wallSegment} from './Geometry.js';
import {Door} from './Door.js';
export function slabPieces(poly,holes=[],clip=null){const xs=[...new Set([...poly.map(p=>p[0]),...(clip||[]).map(p=>p[0]),...holes.flatMap(h=>[h[0],h[2]])])].sort((a,b)=>a-b),zs=[...new Set([...poly.map(p=>p[1]),...(clip||[]).map(p=>p[1]),...holes.flatMap(h=>[h[1],h[3]])])].sort((a,b)=>a-b);const out=[];for(let i=0;i<xs.length-1;i++)for(let j=0;j<zs.length-1;j++){const x=(xs[i]+xs[i+1])/2,z=(zs[j]+zs[j+1])/2;if(insidePolygon(x,z,poly)&&(!clip||insidePolygon(x,z,clip))&&!holes.some(h=>x>h[0]&&x<h[2]&&z>h[1]&&z<h[3]))out.push([xs[i],zs[j],xs[i+1],zs[j+1]]);}return out;}
export function buildSlabs(parent,floor,m,solids){const poly=[FRONT_POLYGON,FIRST_POLYGON,SECOND_POLYGONS[0]][floor];const g=group(parent,'floorSlab');for(const [x,z,x2,z2]of slabPieces(poly,HOLES[floor])){box(g,'Slab',(x+x2)/2,-.12,(z+z2)/2,x2-x,.24,z2-z,m.brick,solids);box(g,'Floor finish',(x+x2)/2,.007,(z+z2)/2,x2-x,.014,z2-z,floor?m.carpet:m.wood);}return g;}
export function buildWalls(parent,floor,m,solids,doors,specs=WALLS[floor]){const exterior=group(parent,'externalWalls'),interior=group(parent,'internalWalls');for(const spec of specs){const g=group(spec.side?exterior:interior,'Wall assembly');g.userData.side=spec.side;const dx=spec.b[0]-spec.a[0],dz=spec.b[1]-spec.a[1],len=Math.hypot(dx,dz),angle=Math.atan2(dz,dx),t=spec.side?.32:.14,H=floor===2?(spec.side?2.25:2.65):(spec.side?3.15:2.91);
const at=d=>({x:spec.a[0]+dx*d/len,z:spec.a[1]+dz*d/len});const segment=(a,b,y,h)=>{if(b-a<.002||h<.002)return;const p=at((a+b)/2);wallSegment(g,p.x,p.z,b-a,h,t,angle,spec.side?m.brick:m.wall,y,solids);if(spec.side){let nx=-dz/len,nz=dx/len;const inward=spec.side==='rear'?[0,1]:spec.side==='front'?[0,-1]:spec.side==='left'?[1,0]:[-1,0];const s=Math.sign(nx*inward[0]+nz*inward[1]);wallSegment(g,p.x+nx*s*(t/2+.008),p.z+nz*s*(t/2+.008),b-a,h,.016,angle,m.wall,y);}if(y===0&&!spec.side)for(const s of [-1,1])wallSegment(g,p.x-dz/len*s*(t/2+.01),p.z+dx/len*s*(t/2+.01),b-a,.11,.02,angle,m.white,0);};let cursor=0;
for(const op of [...spec.openings].sort((a,b)=>a.at-b.at)){segment(cursor,op.at,0,H);const base=op.type==='w'?op.sill:0,top=op.full?H:op.type==='w'?base+op.height:2.15;segment(op.at,op.at+op.width,top,H-top);if(op.type==='w')segment(op.at,op.at+op.width,0,base);if(op.type!=='o'){const p=at(op.at),assembly=group(g,op.type==='w'?'Window frame':'Door frame');assembly.position.set(p.x,0,p.z);assembly.rotation.y=-angle;const mat=op.type==='w'?m.frame:m.white;for(const x of [0,op.width])box(assembly,'Jamb',x,(base+top)/2,0,.075,top-base+.1,t+.08,mat);box(assembly,'Lintel',op.width/2,top,0,op.width+.13,.075,t+.08,mat);
if(op.type==='w'){box(assembly,'Stone sill',op.width/2,base,0,op.width+.22,.09,t+.22,(floor===2?m.frame:m.stone));box(assembly,'Glazing',op.width/2,(base+top)/2,0,op.width-.08,top-base-.06,.012,m.glass);for(const x of op.width>2?[op.width/3,op.width*2/3]:[op.width/2])box(assembly,'Mullion',x,(base+top)/2,0,.05,top-base,.08,m.frame);box(assembly,'Transom',op.width/2,top-.42,0,op.width,.05,.08,m.frame);for(const x of [-.09,op.width+.09])box(assembly,'Stone window surround',x,(base+top)/2,0,.1,top-base+.24,t+.05,(floor===2?m.frame:m.stone));box(assembly,'Stone head',op.width/2,top+.11,0,op.width+.27,.13,t+.07,(floor===2?m.frame:m.stone));
}else if(op.width>1.55){doors.push(new Door(g,{...op,id:op.id+'-L',width:op.width/2},p,angle,m));doors.push(new Door(g,{...op,id:op.id+'-R',width:op.width/2,swing:-op.swing},at(op.at+op.width),angle+Math.PI,m));}else doors.push(new Door(g,op,p,angle,m));}cursor=op.at+op.width;}segment(cursor,len,0,H);}return {exterior,interior};}
export function rail(parent,m,solids,a,b,y=0){const dx=b[0]-a[0],dz=b[1]-a[1],length=Math.hypot(dx,dz),angle=Math.atan2(dz,dx);wallSegment(parent,(a[0]+b[0])/2,(a[1]+b[1])/2,length,.07,.07,angle,m.wood,y+.96);for(let i=0;i<=Math.ceil(length/.13);i++){let t=i/Math.ceil(length/.13);box(parent,'Baluster',a[0]+dx*t,y+.48,a[1]+dz*t,.028,.96,.028,m.frame);}const barrier=wallSegment(parent,(a[0]+b[0])/2,(a[1]+b[1])/2,length,.94,.04,angle,m.frame,y,solids);barrier.visible=false;}
export function buildStairs(floors,m,solids){for(const s of STAIRS){const g=group(floors[s.floor],'stairs '+s.id),dx=s.b[0]-s.a[0],dz=s.b[1]-s.a[1],length=Math.hypot(dx,dz),angle=Math.atan2(dz,dx),rise=(s.y1-s.y0)/s.n,run=length/s.n,base=HOUSE.levels[s.floor];for(let i=0;i<s.n;i++){const t=(i+.5)/s.n;const mesh=box(g,'Tread and riser',s.a[0]+dx*t,s.y0-base+(i+.5)*rise,s.a[1]+dz*t,run,rise,s.width,m.wood);mesh.rotation.y=-angle;}
// Rail follows the outside edge; no overlapping nosing meshes.
const nx=-dz/length*(s.width/2+.025),nz=dx/length*(s.width/2+.025);const a=new THREE.Vector3(s.a[0]+nx,s.y0-base+.95,s.a[1]+nz),b=new THREE.Vector3(s.b[0]+nx,s.y1-base+.95,s.b[1]+nz);const rod=new THREE.Mesh(new THREE.CylinderGeometry(.03,.03,a.distanceTo(b),10),m.wood);rod.position.copy(a).add(b).multiplyScalar(.5);rod.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize());g.add(rod);for(let i=0;i<=s.n;i++){const t=i/s.n;box(g,'Stair spindle',a.x+(b.x-a.x)*t,s.y0-base+(s.y1-s.y0)*t+.46,a.z+(b.z-a.z)*t,.027,.92,.027,m.frame);}}
box(floors[0],'Quarter landing',8.53,.965,12.48,1.12,.17,1.12,m.wood);
const g=group(floors[1],'void balustrade');rail(g,m,solids,[5.55,11.91],[7.94,11.91]);rail(g,m,solids,[7.92,8.66],[7.92,11.91]);rail(g,m,solids,[5.50,11.94],[5.50,13.25]);
const u=group(floors[2],'upper balustrade');rail(u,m,solids,[8.0,6.97],[8.0,7.9]);rail(u,m,solids,[8.0,7.93],[9.07,7.93]);
}
export function hipRoof(parent,m,x0,x1,z0,z1,y,h){const g=group(parent,'Hipped roof'),inset=Math.min((x1-x0)/3,(z1-z0)/3),mid=(z0+z1)/2;
 const faces=[{p:[[x0,z0],[x1,z0],[x1-inset,mid],[x0+inset,mid]],height:(x,z)=>y+h*(z-z0)/(mid-z0),end:'rear'},{p:[[x0+inset,mid],[x1-inset,mid],[x1,z1],[x0,z1]],height:(x,z)=>y+h*(z1-z)/(z1-mid),end:'front'},{p:[[x0,z0],[x0+inset,mid],[x0,z1]],height:(x,z)=>y+h*(x-x0)/inset},{p:[[x1,z0],[x1,z1],[x1-inset,mid]],height:(x,z)=>y+h*(x1-x)/inset}];
 for(const face of faces){const shape=new THREE.Shape(face.p.map(p=>new THREE.Vector2(...p)));if(x1>14&&face.end){for(const [a,b]of[[3.18,5.30],[9.12,10.91]]){const za=face.end==='front'?12.27:3.40,zb=face.end==='front'?14.29:5.94;shape.holes.push(new THREE.Path([new THREE.Vector2(a,za),new THREE.Vector2(a,zb),new THREE.Vector2(b,zb),new THREE.Vector2(b,za)]));}}
 const geo=new THREE.ShapeGeometry(shape),pos=geo.attributes.position,uv=geo.attributes.uv;for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getY(i);pos.setXYZ(i,x,face.height(x,z),z);uv.setXY(i,x/2,z/2);}geo.computeVertexNormals();const mesh=new THREE.Mesh(geo,m.roof);mesh.castShadow=true;mesh.receiveShadow=true;g.add(mesh);}
 for(const z of[z0,z1])box(g,'Gutter',(x0+x1)/2,y-.06,z,x1-x0,.16,.16,m.frame);for(const x of[x0,x1])box(g,'Side gutter',x,y-.06,(z0+z1)/2,.16,.16,z1-z0,m.frame);return g;}
