import * as THREE from 'three';
import {HOUSE,ROOMS,HOLES,FRONT_POLYGON,FIRST_POLYGON,SECOND_POLYGONS,REFERENCES,D,W} from '../data/houseData.js';
import {box,group,cylinder} from './Geometry.js';
import {buildSlabs,buildWalls,buildStairs,slabPieces,hipRoof} from './Architecture.js';
import {furnish} from '../furniture/FurnitureFactory.js';
export class House{
 constructor(m,manager){this.root=new THREE.Group();this.root.name='Brookheaven';this.staticMeshes=[];this.furnitureMeshes=[];this.doors=[];this.roomMeshes=[];this.floors=[];this.parts=[];this.references=[];this.lights=[];
 for(let i=0;i<3;i++){const f=group(this.root,['groundFloor','firstFloor','secondFloor'][i]);f.position.y=HOUSE.levels[i];this.floors.push(f);const slab=buildSlabs(f,i,m,this.staticMeshes);const walls=buildWalls(f,i,m,this.staticMeshes,this.doors);const furniture=group(f,'furniture'),zones=group(f,'roomZones'),ceilings=group(f,'ceilings');
 if(i<2){const poly=i===0?FRONT_POLYGON:FIRST_POLYGON;for(const q of slabPieces(poly,HOLES[i+1]))box(ceilings,'Ceiling',(q[0]+q[2])/2,2.90,(q[1]+q[3])/2,q[2]-q[0],.04,q[3]-q[1],m.white);}
 else {for(const x of[2.38,12.18]){const slope=box(ceilings,'Sloping attic ceiling',x,1.78,9.10,2.35,.12,6.1,m.wall);slope.rotation.z=x<7?-.62:.62;} }
 for(const r of ROOMS.filter(r=>r.floor===i)){const poly=[[r.x,r.z],[r.x+r.w,r.z],[r.x+r.w,r.z+r.d],[r.x,r.z+r.d]];for(const q of slabPieces(poly,HOLES[i],[FRONT_POLYGON,FIRST_POLYGON,SECOND_POLYGONS[0]][i])){const mat=(r.type.includes('bath')||['wc','ensuite'].includes(r.type)?m.tile:(i?m.carpet:m.wood)).clone();const mesh=box(zones,r.name,(q[0]+q[2])/2,.019,(q[1]+q[3])/2,q[2]-q[0]-.025,.009,q[3]-q[1]-.025,mat);mesh.userData.room=r;this.roomMeshes.push(mesh);}furnish(furniture,r,m,this.furnitureMeshes);}
 this.parts.push({...walls,slab,furniture,zones,ceilings});const ref=REFERENCES[i];if(typeof document!=='undefined')new THREE.TextureLoader(manager).load('./references/'+ref.file,tex=>{tex.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(ref.pixels[0]/ref.scale,ref.pixels[1]/ref.scale),new THREE.MeshBasicMaterial({map:tex,transparent:true,opacity:.5,depthWrite:false,side:THREE.DoubleSide}));mesh.rotation.x=-Math.PI/2;mesh.position.set(ref.offset[0]+(ref.pixels[0]/2-ref.origin[0])/ref.scale,.065,ref.offset[1]+(ref.pixels[1]/2-ref.origin[1])/ref.scale);mesh.visible=false;f.add(mesh);this.references[i]=mesh;});}
 // Trim attic wall/ceiling vertices to the hip envelope; dormer volumes retain full height.
 const roofLimit=(x,z)=>{let y=6.17+3.55*Math.max(0,Math.min(1,(x+.55)/3.9,(14.3-x)/3.9,(z-2.95)/5.85,(14.65-z)/5.85));if(((x>3.08&&x<5.40)||(x>9.02&&x<11.01))&&(z<6.05||z>12.15))y=Math.max(y,8.42);return y-.035;};
 this.root.updateMatrixWorld(true);
 for(const part of [this.parts[2].exterior,this.parts[2].interior,this.parts[2].ceilings])part.traverse(o=>{if(!o.isMesh)return;const geo=o.geometry.clone(),pos=geo.attributes.position,inv=o.matrixWorld.clone().invert();for(let i=0;i<pos.count;i++){const v=new THREE.Vector3().fromBufferAttribute(pos,i).applyMatrix4(o.matrixWorld);v.y=Math.min(v.y,Math.max(6.34,roofLimit(v.x,v.z)));v.applyMatrix4(inv);pos.setXYZ(i,v.x,v.y,v.z);}pos.needsUpdate=true;geo.computeVertexNormals();o.geometry=geo;});
 buildStairs(this.floors,m,this.staticMeshes);
 this.roof=group(this.root,'roof');hipRoof(this.roof,m,-.55,14.30,2.95,14.65,6.17,3.55);
 // Flat-roofed dormer boxes as in the exterior image, repeated to the rear plan.
 for(const x of[4.24,10.02])for(const z of[4.65,13.20]){const g=group(this.roof,'Dormer');box(g,'Dormer cap',x,8.56,z,2.25,.19,2.30,m.frame);for(const side of[-1,1])box(g,'Dormer cheek',x+side*.99,7.80,z,.14,1.45,2.2,m.frame);box(g,'Dormer glazing',x,7.8,z+(z>8?1.09:-1.09),1.82,1.3,.03,m.glass);for(const dx of[-.94,0,.94])box(g,'Dormer frame',x+dx,7.8,z+(z>8?1.11:-1.11),.07,1.45,.07,m.frame);}
 this.extensionRoof=group(this.floors[0],'rear extension roof');box(this.extensionRoof,'Flat extension roof',6.88,3.03,1.68,14.15,.16,3.8,m.frame);
 this.details=group(this.root,'exteriorDetails');for(const x of[5.3,8.1]){box(this.details,'Entrance stone column',x,1.22,14.46,.25,2.44,.42,m.stone);box(this.details,'Column base',x,.14,14.46,.40,.28,.52,m.stone);box(this.details,'Column capital',x,2.46,14.46,.43,.18,.60,m.stone);}box(this.details,'Entrance entablature',6.70,2.65,14.46,3.23,.23,.72,m.stone);box(this.details,'Entrance canopy',6.7,2.82,14.42,3.40,.11,.91,m.frame);
 for(const x of[-.1,13.86])for(const z of[3.52,13.13])box(this.details,'Downpipe',x,3.0,z,.08,6,.08,m.frame);
 this.landscape=group(this.root,'landscape');box(this.landscape,'Plot',3.3,-.2,17,42,.36,64,m.grass,this.staticMeshes);box(this.landscape,'Driveway',2.5,-.013,31,35,.025,34,m.asphalt);box(this.landscape,'Rear terrace',7,-.005,-2.1,15,.04,4,m.paving);box(this.landscape,'Patio',-1.95,.0,11.3,3.76,.045,4.53,m.paving);box(this.landscape,'Garage path',-3.5,-.005,15,3,.04,8,m.paving);box(this.landscape,'Front apron',6.8,.008,14.9,14,.035,1.3,m.paving);
 for(const x of[-16,21])box(this.landscape,'Boundary hedge',x,.7,17,.7,1.4,60,m.leaf);for(const z of[-13,48])box(this.landscape,'Boundary coping',3,.5,z,36,1,.35,m.brick);
 let seed=24;const rand=()=>((seed=seed*16807%2147483647)/2147483647);const tg=new THREE.IcosahedronGeometry(1,2),trees=new THREE.InstancedMesh(tg,m.leaf,54),dummy=new THREE.Object3D();for(let i=0;i<18;i++){const x=i<9?-12-rand()*3:17+rand()*2,z=-10+rand()*33;cylinder(this.landscape,x,1.7,z,.16,3.4,m.bark);for(let j=0;j<3;j++){dummy.position.set(x+(rand()-.5)*1.4,2.5+j*.8,z+(rand()-.5)*1.4);dummy.scale.set(1.3+rand(),1.5+rand(),1.3+rand());dummy.updateMatrix();trees.setMatrixAt(i*3+j,dummy.matrix);}}trees.castShadow=true;this.landscape.add(trees);
 box(this.landscape,'Patio dining table',-2,.76,10.6,1.65,.07,.85,m.wood,this.furnitureMeshes);for(const x of[-2.5,-1.5])for(const z of[9.85,11.35]){box(this.landscape,'Outdoor chair seat',x,.44,z,.5,.12,.5,m.sofa,this.furnitureMeshes);box(this.landscape,'Outdoor chair back',x,.76,z+(z>10?.22:-.22),.5,.55,.06,m.sofa);}for(const x of[4.85,8.55]){box(this.landscape,'Entrance planter',x,.35,14.8,.55,.7,.55,m.frame);cylinder(this.landscape,x,1.03,14.8,.3,.8,m.leaf);}
 this.garage=group(this.root,'garage');this.garage.position.set(-8.4,0,17.85);box(this.garage,'Garage slab',2.695,-.12,4.675,5.39,.24,9.35,m.paving,this.staticMeshes);buildWalls(this.garage,0,m,this.staticMeshes,this.doors,[{a:[0,0],b:[5.39,0],side:'rear',openings:[D(3.6,1,'garage-person')]},{a:[0,0],b:[0,9.35],side:'left',openings:[]},{a:[5.39,0],b:[5.39,9.35],side:'right',openings:[W(1.5,1.6),W(5.5,1.6)]},{a:[0,9.35],b:[5.39,9.35],side:'front',openings:[D(.55,4.3,'garage-main')]}]);hipRoof(this.garage,m,-.3,5.69,-.3,9.65,2.98,1.6);
 for(const [x,z]of[[4.55,14.0],[8.8,14.0],[.3,13.6],[13.5,13.6],[-8.3,27],[-3.2,27],[-11,2],[17,2],[-11,15],[17,15],[2,-1],[12,-1]]){box(this.landscape,'Outdoor luminaire',x,.8,z,.10,.55,.10,m.light);const l=new THREE.PointLight('#ffcc86',0,6,2);l.position.set(x,1.1,z+.2);this.landscape.add(l);this.lights.push(l);}
 for(const r of ROOMS.filter(r=>!['pantry','wc','landing'].includes(r.type))){const l=new THREE.PointLight('#ffe0b0',0,6,2);l.position.set(r.x+r.w/2,r.floor===2?1.45:2.55,r.z+r.d/2);this.floors[r.floor].add(l);this.lights.push(l);}
 this.grid=new THREE.GridHelper(40,40,0x7a7461,0x989587);this.grid.position.set(6,.07,8);this.grid.visible=false;this.root.add(this.grid);this.root.updateMatrixWorld(true);
 }
 apply(state){for(let i=0;i<3;i++){const p=this.parts[i];this.floors[i].visible=state.floor==='all'||state.floor==='roof'||Number(state.floor)===i;p.furniture.visible=state.furniture;p.ceilings.visible=!state.explode&&!state.doll&&state.floor==='all'&&!state.cut;p.exterior.children.forEach(g=>g.visible=!(state.doll&&['front','left'].includes(g.userData.side))&&g.userData.side!==state.cut);if(this.references[i]){this.references[i].visible=state.reference;this.references[i].material.opacity=state.opacity;}}
 this.roof.visible=state.roof&&!state.doll&&(state.floor==='all'||state.floor==='roof');this.extensionRoof.visible=this.roof.visible&&!state.explode;this.details.visible=state.floor==='all'&&!state.doll&&!state.cut;this.garage.visible=state.floor==='all'||state.floor==='0';this.landscape.visible=true;}
 update(dt,state){for(let i=0;i<3;i++)this.floors[i].position.y=THREE.MathUtils.damp(this.floors[i].position.y,HOUSE.levels[i]+(state.explode?i*4.5:0),6,dt);this.roof.position.y=THREE.MathUtils.damp(this.roof.position.y,state.explode?13.5:0,6,dt);for(const d of this.doors)d.update(dt);}
}
