import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {House} from './house/House.js';
import {createMaterials} from './materials/Materials.js';
import {CollisionWorld} from './collision/CollisionWorld.js';
import {PlayerController} from './controls/PlayerController.js';
import {HOUSE,ROOMS,FLOOR_NAMES,REFERENCES,WALLS,HOLES} from './data/houseData.js';
import './style.css';
const $=id=>document.getElementById(id),scene=new THREE.Scene();scene.background=new THREE.Color('#a6b7b7');scene.fog=new THREE.Fog('#a6b7b7',65,145);
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;$('scene').appendChild(renderer.domElement);
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.08,190),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.49;controls.minDistance=3;controls.maxDistance=70;
const hemi=new THREE.HemisphereLight('#dce8ef','#5d6650',2.1);scene.add(hemi);const sun=new THREE.DirectionalLight('#fff0d7',3.4);sun.position.set(-12,27,22);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-25,right:25,top:28,bottom:-28,near:1,far:90});sun.shadow.normalBias=.035;sun.shadow.bias=-.00015;scene.add(sun);sun.target.position.set(6,0,8);scene.add(sun.target);
const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.02).texture;scene.environmentIntensity=.26;
const state={floor:'all',doll:false,explode:false,roof:true,furniture:true,labels:false,dimensions:false,reference:false,opacity:.5,cut:'',light:'day',measure:false,touch:matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0};
const manager=new THREE.LoadingManager();manager.onProgress=(url,n,total)=>{$('progress').value=n/total*100;$('percent').textContent=Math.round(n/total*100)+'%';};manager.onLoad=()=>{$('progress').value=100;$('percent').textContent='100%';$('loading').style.opacity='0';setTimeout(()=>$('loading').hidden=true,520);};manager.onError=url=>notify('Reference unavailable: '+url.split('/').pop());const materials=createMaterials(),house=new House(materials,manager);scene.add(house.root);const world=new CollisionWorld(house),player=new PlayerController(camera,renderer.domElement,world);
let transition=null,selected=null,showMap=false,measurePoints=[],measureLabels=[],dimLabels=[],dimGroup=new THREE.Group(),measureGroup=new THREE.Group(),colliderHelpers=null;scene.add(dimGroup,measureGroup);const labelItems=[];
const status=text=>{$('status').textContent=text;};function notify(text){status(text);}
function cameraTo(pos,target){transition={pos:new THREE.Vector3(...pos),target:new THREE.Vector3(...target)};}
function exterior(which='front'){const mobile=innerWidth/innerHeight<1;const views={front:[[mobile?-17:-19,mobile?23:19,mobile?44:36],[6,3.4,9]],rear:[[25,19,-20],[6,2.8,5]],garage:[[-20,12,35],[-5.7,1.4,22]],top:[[6.8,34,8.7],[6.8,0,8.71]]};cameraTo(...views[which]);}
function apply(){house.apply(state);world.furnitureVisible=state.furniture;for(const b of document.querySelectorAll('[data-floor]'))b.classList.toggle('active',b.dataset.floor===state.floor&&!state.doll);$('doll').classList.toggle('active',state.doll);for(const [id,key]of[['explode','explode'],['furniture','furniture'],['label-toggle','labels'],['dimensions','dimensions'],['reference','reference'],['measure','measure']])$(id).setAttribute('aria-pressed',String(state[key]));$('roof').textContent=state.roof?'Hide roof':'Show roof';$('cut').value=state.cut;$('opacity').value=state.opacity;updateDimensions();}
function explore(){$('intro').hidden=true;}
function setFloor(floor){selected=null;$('room-panel').hidden=true;$('rooms').value='';for(const mesh of house.roomMeshes)mesh.material.emissive.set('#000');if(player.active)exitWalk();explore();state.floor=floor;state.doll=false;state.explode=false;state.cut='';apply();if(floor==='all')exterior();else if(floor==='roof')cameraTo([23,19,31],[6.8,6.4,9]);else{const y=HOUSE.levels[Number(floor)];cameraTo([22,24+y,28],[6.8,y,8.5]);$('calibration').textContent=REFERENCES[Number(floor)].calibration;}}
function label(text,cls='room-label'){const el=document.createElement('div');el.className=cls;el.textContent=text;$('labels').appendChild(el);return el;}
for(const r of ROOMS)labelItems.push({r,el:label(r.name)});
function projectLabel(el,p,visible){const v=p.clone().project(camera);el.hidden=!visible||v.z>1||v.z<-1;if(!el.hidden){el.style.left=(v.x*.5+.5)*innerWidth+'px';el.style.top=(-v.y*.5+.5)*innerHeight+'px';}}
function drawLine(parent,points,color='#d5bd8e'){const g=new THREE.BufferGeometry().setFromPoints(points.map(p=>new THREE.Vector3(...p)));const line=new THREE.Line(g,new THREE.LineBasicMaterial({color,depthTest:false}));line.renderOrder=5;parent.add(line);return line;}
function cleanGroup(g){g.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});g.clear();}
function updateDimensions(){cleanGroup(dimGroup);for(const d of dimLabels)d.el.remove();dimLabels=[];if(!state.dimensions||player.active)return;const rs=selected?[selected]:[ROOMS.find(r=>String(r.floor)===state.floor)].filter(Boolean);for(const r of rs){const y=HOUSE.levels[r.floor]+.1;for(const [a,b,text]of[[[r.x+.2,y,r.z+.3],[r.x+r.w-.2,y,r.z+.3],r.dimensions.includes('×')?r.dimensions.split(' × ')[0]+' m':r.w.toFixed(2)+' m (approx.)'],[[r.x+.3,y,r.z+.2],[r.x+.3,y,r.z+r.d-.2],r.dimensions.includes('×')?r.dimensions.split(' × ')[1]:r.d.toFixed(2)+' m']]){drawLine(dimGroup,[a,b]);for(const p of[a,b])drawLine(dimGroup,[[p[0]-.12,y,p[2]-.12],[p[0]+.12,y,p[2]+.12]]);const mid=new THREE.Vector3(...a).add(new THREE.Vector3(...b)).multiplyScalar(.5);dimLabels.push({el:label(text,'dim-label'),p:mid,floor:r.floor});}}
if(!rs.length)notify('Select a floor or room to show dimensions.');}
function roomSelect(r){explore();selected=r;if(!player.active){state.floor=String(r.floor);state.roof=false;state.doll=false;state.explode=false;apply();cameraTo([r.x+r.w/2+4,HOUSE.levels[r.floor]+Math.max(7,r.w),r.z+r.d/2+5],[r.x+r.w/2,HOUSE.levels[r.floor]+.5,r.z+r.d/2]);}$('room-panel').hidden=false;$('room-name').textContent=r.name;$('room-floor').textContent=FLOOR_NAMES[r.floor];$('room-size').textContent=r.dimensions;$('rooms').value=r.id;for(const mesh of house.roomMeshes){mesh.material.emissive.set(mesh.userData.room===r?'#6e5c2d':'#000');mesh.material.emissiveIntensity=.18;}updateDimensions();}
function restoreAssembly(){Object.assign(state,{floor:'all',roof:true,doll:false,explode:false,cut:'',reference:false,measure:false});apply();for(let i=0;i<3;i++)house.floors[i].position.y=HOUSE.levels[i];house.roof.position.y=0;house.root.updateMatrixWorld(true);world.refresh();}
function startWalk(r=null){explore();restoreAssembly();transition=null;controls.enabled=false;camera.fov=innerWidth/innerHeight<1?70:60;camera.updateProjectionMatrix();player.start('front');player.position.z=innerWidth/innerHeight<1?40:30;player.pitch=.15;player.syncCamera(1);if(r){const candidates=[[r.x+.8,r.z+r.d/2],[r.x+r.w-.8,r.z+r.d/2],[r.x+r.w/2,r.z+r.d-.7],[r.x+r.w/2,r.z+.7]];const p=candidates.find(([x,z])=>world.clear(new THREE.Vector3(x,HOUSE.levels[r.floor],z))&&Number.isFinite(world.support(new THREE.Vector3(x,HOUSE.levels[r.floor],z),.1,HOUSE.levels[r.floor]+.05,HOUSE.levels[r.floor]-.1)));if(p){player.position.set(p[0],HOUSE.levels[r.floor],p[1]);player.eyeY=player.position.y+1.68;player.yaw=Math.atan2(p[0]-(r.x+r.w/2),p[1]-(r.z+r.d/2));player.pitch=-.12;player.syncCamera(1);}else notify('No clear room start. Walk in from the entrance.');}document.body.classList.add('walking');$('walk-ui').hidden=false;$('walk-instructions').hidden=false;$('crosshair').hidden=false;$('touch-controls').hidden=!state.touch;$('tools').hidden=true;status('Walk · W A S D / joystick · E / button to open doors');}
function exitWalk(){player.stop();camera.fov=48;camera.updateProjectionMatrix();controls.enabled=true;document.body.classList.remove('walking');for(const id of['walk-ui','walk-instructions','crosshair','touch-controls'])$(id).hidden=true;exterior();}
function interact(){house.root.updateMatrixWorld(true);let best=null,dist=2.5;for(const d of house.doors){const p=d.pivot.getWorldPosition(new THREE.Vector3());p.y+=1;const n=p.distanceTo(camera.position);if(n<dist){best=d;dist=n;}}if(best){best.toggle();status((best.open?'Opening ':'Closing ')+best.id.replaceAll('-',' '));}else status('Move closer to a door to open or close it.');}player.onInteract=interact;
for(const r of ROOMS){const o=document.createElement('option');o.value=r.id;o.textContent=FLOOR_NAMES[r.floor]+' · '+r.name;$('rooms').appendChild(o);}$('rooms').onchange=e=>{const r=ROOMS.find(r=>r.id===e.target.value);if(r)roomSelect(r);};$('views').onchange=e=>{if(player.active)exitWalk();restoreAssembly();exterior(e.target.value);};
for(const b of document.querySelectorAll('[data-floor]'))b.onclick=()=>setFloor(b.dataset.floor);
$('explore').onclick=()=>{explore();setFloor('0');};$('walk').onclick=$('start-walk').onclick=()=>startWalk();$('return-entrance').onclick=()=>startWalk();$('exit-walk').onclick=exitWalk;$('enter-room').onclick=()=>startWalk(selected);$('close-room').onclick=()=>{$('room-panel').hidden=true;selected=null;updateDimensions();};
$('menu-toggle').onclick=()=>{$('tools').hidden=!$('tools').hidden;};$('close-tools').onclick=()=>$('tools').hidden=true;$('help').onclick=()=>$('help-dialog').showModal();$('close-help').onclick=()=>$('help-dialog').close();
$('doll').onclick=()=>{if(player.active)exitWalk();explore();state.doll=!state.doll;state.floor='all';state.roof=!state.doll;apply();cameraTo([-18,19,31],[6.5,4.1,8.5]);};
for(const [id,key]of[['explode','explode'],['roof','roof'],['furniture','furniture'],['label-toggle','labels'],['dimensions','dimensions'],['reference','reference']])$(id).onclick=()=>{explore();if(player.active&&['explode','reference'].includes(key))exitWalk();state[key]=!state[key];if(key==='explode'){state.floor='all';state.doll=false;state.roof=true;cameraTo([-24,state.explode?31:19,39],[6.5,state.explode?11:4,8]);}if(key==='reference'&&state.reference&&state.floor==='all')state.floor='0';apply();};
$('opacity').oninput=e=>{state.opacity=Number(e.target.value);apply();};$('cut').onchange=e=>{if(player.active)exitWalk();state.cut=e.target.value;state.roof=!state.cut;explore();apply();};$('roof-opacity').oninput=e=>{materials.roof.transparent=Number(e.target.value)<1;materials.roof.opacity=Number(e.target.value);materials.roof.depthWrite=Number(e.target.value)===1;};
$('measure').onclick=()=>{state.measure=!state.measure;measurePoints=[];explore();apply();status(state.measure?'Measure: select two points on visible architecture.':'Measurement paused.');};$('clear-measure').onclick=()=>{measurePoints=[];cleanGroup(measureGroup);measureLabels.forEach(l=>l.el.remove());measureLabels=[];status('Measurements cleared');};
$('map-toggle').onclick=()=>{showMap=!showMap;$('minimap').hidden=!showMap;};$('touch-toggle').onclick=()=>{state.touch=!state.touch;$('touch-controls').hidden=!(state.touch&&player.active);};$('grid').onclick=()=>house.grid.visible=!house.grid.visible;
$('bounds').onclick=()=>{if(!colliderHelpers){colliderHelpers=new THREE.Group();for(const s of world.static)colliderHelpers.add(new THREE.Box3Helper(s.box,0xffaa33));scene.add(colliderHelpers);}else colliderHelpers.visible=!colliderHelpers.visible;};
$('reset').onclick=()=>{if(player.active)exitWalk();selected=null;restoreAssembly();state.labels=false;state.dimensions=false;apply();$('room-panel').hidden=true;exterior();};$('screenshot').onclick=()=>{renderer.render(scene,camera);const a=document.createElement('a');a.href=renderer.domElement.toDataURL('image/png');a.download='Brookheaven-view.png';a.click();};
const lighting={day:{sky:'#a6b7b7',sun:'#fff0d7',power:3.4,hemi:2.1,lamps:0},evening:{sky:'#6d7980',sun:'#ffc384',power:1.5,hemi:.9,lamps:14},night:{sky:'#14232f',sun:'#b2c8e6',power:.30,hemi:.35,lamps:23}};
for(const b of document.querySelectorAll('[data-light]'))b.onclick=()=>{state.light=b.dataset.light;for(const q of document.querySelectorAll('[data-light]'))q.classList.toggle('active',q===b);};
const ray=new THREE.Raycaster();let down=null;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);const visible=o=>{while(o){if(!o.visible)return false;o=o.parent;}return true;};renderer.domElement.addEventListener('pointerup',e=>{if(player.active||!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;ray.setFromCamera(new THREE.Vector2(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1),camera);const hits=ray.intersectObject(house.root,true).filter(h=>visible(h.object)&&h.object.isMesh&&!h.object.name.includes('Glass'));if(!hits.length)return;
if(state.measure){const p=hits[0].point.clone();measurePoints.push(p);if(measurePoints.length===2){const[a,b]=measurePoints,n=a.distanceTo(b);drawLine(measureGroup,[a.toArray(),b.toArray()]);measureLabels.push({el:label(n.toFixed(3)+' m / '+Math.round(n*1000)+' mm','dim-label'),p:a.clone().add(b).multiplyScalar(.5)});status('Measured '+n.toFixed(3)+' m ('+Math.round(n*1000)+' mm)');measurePoints=[];}else status('First point set. Choose the second point.');return;}
let d=hits[0].object.userData.door;if(d){d.toggle();return;}const hit=hits.find(h=>h.object.userData.room);if(hit)roomSelect(hit.object.userData.room);});
const map=$('map').getContext('2d');function updateMap(){if(!showMap)return;const f=player.active?(player.position.y>6?2:player.position.y>2.85?1:0):(Number.isInteger(Number(state.floor))?Number(state.floor):selected?.floor||0);$('map-title').textContent=FLOOR_NAMES[f].toUpperCase();map.clearRect(0,0,300,260);const X=x=>25+x*17,Z=z=>8+z*16;for(const r of ROOMS.filter(r=>r.floor===f)){map.fillStyle=r===selected?'#897f5f':'#d4d9ca';map.fillRect(X(r.x),Z(r.z),r.w*17,r.d*16);map.fillStyle='#253c33';map.font='9px Arial';map.fillText(r.name.replace('Bedroom','Bed').replace('Principal','Main'),X(r.x)+3,Z(r.z+r.d/2));}map.fillStyle='#19322e';for(const h of HOLES[f])map.fillRect(X(h[0]),Z(h[1]),(h[2]-h[0])*17,(h[3]-h[1])*16);map.strokeStyle='#84958b';map.lineWidth=2;for(const w of WALLS[f]){map.beginPath();map.moveTo(X(w.a[0]),Z(w.a[1]));map.lineTo(X(w.b[0]),Z(w.b[1]));map.stroke();}if(player.active){map.fillStyle='#edb965';map.beginPath();map.arc(X(player.position.x),Z(player.position.z),4,0,Math.PI*2);map.fill();map.strokeStyle='#edb965';map.beginPath();map.moveTo(X(player.position.x),Z(player.position.z));map.lineTo(X(player.position.x-Math.sin(player.yaw)*.8),Z(player.position.z-Math.cos(player.yaw)*.8));map.stroke();}}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);if(!$('intro').hidden)exterior();});
addEventListener('keydown',e=>{if(player.active||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.code==='KeyG')$('grid').click();if(e.code==='KeyB'||e.code==='KeyC')$('bounds').click();if(e.code==='KeyF')$('reference').click();if(e.code==='KeyR')$('label-toggle').click();if(e.code==='KeyP')status(camera.position.toArray().map(n=>n.toFixed(2)).join(', ')+' m');});
let last=performance.now(),frame=0;function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;house.update(dt,state);if(player.active){player.update(dt);$('location').textContent=player.currentRoom();}else if(transition){const k=matchMedia('(prefers-reduced-motion:reduce)').matches?1:1-Math.exp(-4*dt);camera.position.lerp(transition.pos,k);controls.target.lerp(transition.target,k);if(camera.position.distanceTo(transition.pos)<.015)transition=null;controls.update();}else controls.update();
const l=lighting[state.light],k=1-Math.exp(-3*dt);scene.background.lerp(new THREE.Color(l.sky),k);scene.fog.color.copy(scene.background);sun.color.lerp(new THREE.Color(l.sun),k);sun.intensity=THREE.MathUtils.lerp(sun.intensity,l.power,k);hemi.intensity=THREE.MathUtils.lerp(hemi.intensity,l.hemi,k);for(const lamp of house.lights)lamp.intensity=THREE.MathUtils.lerp(lamp.intensity,l.lamps,k);materials.light.emissiveIntensity=state.light==='day'?.45:2.3;
for(const item of labelItems){const r=item.r,p=new THREE.Vector3(r.x+r.w/2,house.floors[r.floor].position.y+.35,r.z+r.d/2);projectLabel(item.el,p,state.labels&&!player.active&&house.floors[r.floor].visible);}for(const d of dimLabels){const p=d.p.clone();p.y+=house.floors[d.floor].position.y-HOUSE.levels[d.floor];projectLabel(d.el,p,state.dimensions&&!player.active&&house.floors[d.floor].visible);}for(const l of measureLabels)projectLabel(l.el,l.p,!player.active);if(frame++%8===0)updateMap();renderer.render(scene,camera);}
apply();exterior();camera.position.set(-19,19,36);controls.target.set(6,3.4,9);requestAnimationFrame(animate);
// Explicit inspection hook used by the included browser QA, not an external dependency.
window.brookheaven={scene,house,state,world,player,camera,controls,roomSelect,setFloor,startWalk,exitWalk,apply,renderer};
