import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';
import {House} from '../src/house/House.js';import {CollisionWorld} from '../src/collision/CollisionWorld.js';import {HOLES,STAIRS,ROOMS,HOUSE,FRONT_POLYGON,FIRST_POLYGON,SECOND_POLYGONS} from '../src/data/houseData.js';import {slabPieces} from '../src/house/Architecture.js';
const mats=Object.fromEntries(['brick','roof','wood','carpet','grass','tile','wall','white','frame','door','glass','metal','cabinet','counter','sofa','accent','dark','paving','soil','leaf','light','stone','asphalt','bark'].map(k=>[k,new THREE.MeshStandardMaterial()]));
const house=new House(mats),world=new CollisionWorld(house);const make=(x,y,z)=>({position:new THREE.Vector3(x,y,z),radius:.28,height:1.7,stepHeight:.21,grounded:true});
function walk(p,x,z){for(let i=0;i<2400;i++){const d=new THREE.Vector3(x-p.position.x,0,z-p.position.z);if(d.length()<.035)return true;d.clampLength(0,.03);const old=p.position.clone();world.move(p,d,1/60);if(old.distanceTo(p.position)<.0001)return false;}return false;}
const openAll=()=>{for(const d of house.doors){d.open=true;d.target=d.swing*Math.PI*.49;d.update(1);}house.root.updateMatrixWorld(true);};
test('all three floor slabs exclude shared stair and void holes',()=>{for(let f=1;f<3;f++){const pieces=slabPieces(f===1?FIRST_POLYGON:SECOND_POLYGONS[0],HOLES[f]);for(const h of HOLES[f]){const x=(h[0]+h[2])/2,z=(h[1]+h[3])/2;assert(!pieces.some(q=>x>q[0]&&x<q[2]&&z>q[1]&&z<q[3]));}}});
test('front door blocks when closed and clears when open',()=>{const p=make(6.7,0,15.5);assert(!walk(p,6.7,13.7));const d=house.doors.find(d=>d.id==='front');d.toggle();d.update(1);assert(walk(p,6.7,13.7));});
test('natural stair route reaches both floors and descends',()=>{openAll();const p=make(6.02,0,12.48);const route=[[8.53,12.48],[8.53,11.90],[8.53,8.58],[7.3,8.45],[8.56,8.1],[8.56,7.92],[8.56,6.48],[7.0,6.48],[7.0,7.92],[7.0,8.3]];for(const [x,z]of route)assert(walk(p,x,z),`blocked at ${p.position.toArray()} towards ${x},${z}`);assert(Math.abs(p.position.y-6.3)<.06,`got ${p.position.y}`);for(const [x,z]of route.slice(0,-1).reverse())assert(walk(p,x,z),`descent blocked ${p.position.toArray()} towards ${x},${z}`);assert(walk(p,6.02,12.48));assert(p.position.y<.08);});
test('door openings have realistic widths and all floor dimensions are metric',()=>{assert.equal(ROOMS.filter(r=>r.type==='bed').length,5);assert(ROOMS.every(r=>r.w>1&&r.d>1));assert(house.doors.every(d=>d.width>=.8));});
test('first-floor void has no walkable support near hall front',()=>{assert.equal(world.support(new THREE.Vector3(6.6,3.15,13.5),.08,3.17,3),-Infinity);});
test('furnished floor circulation reaches every room from its landing or hall',()=>{openAll();const step=.12;for(let floor=0;floor<3;floor++){const y=HOUSE.levels[floor],start=[[6.45,10.15],[6.30,9.8],[7.25,8.65]][floor],visited=new Set(),queue=[start],found=new Set();const key=(x,z)=>Math.round((x-start[0])/step)+','+Math.round((z-start[1])/step);visited.add(key(...start));for(let i=0;i<queue.length;i++){const [x,z]=queue[i];for(const r of ROOMS.filter(r=>r.floor===floor))if(x>r.x+.28&&x<r.x+r.w-.28&&z>r.z+.28&&z<r.z+r.d-.28)found.add(r.id);for(const [dx,dz]of[[step,0],[-step,0],[0,step],[0,-step]]){const nx=x+dx,nz=z+dz,k=key(nx,nz);if(nx<-.5||nx>14.1||nz<-.5||nz>14.5||visited.has(k))continue;const p=make(x,y,z);world.move(p,new THREE.Vector3(dx,0,dz),.13);if(Math.hypot(p.position.x-nx,p.position.z-nz)<.025&&Math.abs(p.position.y-y)<.06){visited.add(k);queue.push([nx,nz]);}}}const missed=ROOMS.filter(r=>r.floor===floor&&!found.has(r.id)).map(r=>r.name);assert.deepEqual(missed,[],`Floor ${floor}, ${queue.length} accessible cells`);}});
