import * as THREE from 'three';
import {STARTS,ROOMS,HOUSE} from '../data/houseData.js';
export class PlayerController {
 constructor(camera,canvas,world){this.camera=camera;this.canvas=canvas;this.world=world;this.position=new THREE.Vector3();this.radius=.28;this.height=1.7;this.eyeHeight=1.68;this.stepHeight=.205;this.velocityY=0;this.grounded=true;this.active=false;this.yaw=0;this.pitch=0;this.keys=new Set();this.touchMove={x:0,z:0};this.onInteract=()=>{};this.eyeY=0;canvas.tabIndex=0;
 addEventListener('keydown',e=>{if(!this.active||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();this.keys.add(e.code);if(e.code==='Escape'){this.keys.clear();this.touchMove={x:0,z:0};if(document.pointerLockElement)document.exitPointerLock();}if(e.code==='KeyE'&&!e.repeat)this.onInteract();});addEventListener('keyup',e=>this.keys.delete(e.code));addEventListener('blur',()=>{this.keys.clear();this.touchMove={x:0,z:0};});document.addEventListener('visibilitychange',()=>{this.keys.clear();this.touchMove={x:0,z:0};});
 document.addEventListener('pointerlockchange',()=>{this.keys.clear();document.getElementById('walk-instructions').hidden=document.pointerLockElement===canvas;});document.addEventListener('mousemove',e=>{if(this.active&&document.pointerLockElement===canvas)this.look(e.movementX,e.movementY);});
 canvas.addEventListener('click',()=>{if(!this.active)return;canvas.focus({preventScroll:true});if(canvas.requestPointerLock&&!matchMedia('(pointer:coarse)').matches){try{canvas.requestPointerLock()?.catch(()=>{document.getElementById('walk-instructions').hidden=false;});}catch{document.getElementById('walk-instructions').hidden=false;}}});
 const pad=document.getElementById('joystick');let padId=null;const move=e=>{const b=pad.getBoundingClientRect(),dx=(e.clientX-b.left-b.width/2)/38,dz=(e.clientY-b.top-b.height/2)/38,len=Math.max(1,Math.hypot(dx,dz));this.touchMove={x:dx/len,z:dz/len};pad.firstElementChild.style.transform=`translate(${this.touchMove.x*30}px,${this.touchMove.z*30}px)`;};
 pad.addEventListener('pointerdown',e=>{padId=e.pointerId;pad.setPointerCapture(padId);move(e);document.getElementById('walk-instructions').hidden=true;});pad.addEventListener('pointermove',e=>{if(e.pointerId===padId)move(e);});const release=()=>{padId=null;this.touchMove={x:0,z:0};pad.firstElementChild.style.transform='';};pad.addEventListener('pointerup',release);pad.addEventListener('pointercancel',release);pad.addEventListener('lostpointercapture',release);
 let lookId=null,last;canvas.addEventListener('pointerdown',e=>{if(this.active&&e.button===0&&document.pointerLockElement!==canvas){lookId=e.pointerId;last=[e.clientX,e.clientY];canvas.setPointerCapture(lookId);}});canvas.addEventListener('pointermove',e=>{if(e.pointerId===lookId){this.look((e.clientX-last[0])*1.5,(e.clientY-last[1])*1.5);last=[e.clientX,e.clientY];}});canvas.addEventListener('pointerup',()=>lookId=null);canvas.addEventListener('pointercancel',()=>lookId=null);document.getElementById('touch-interact').onclick=()=>this.onInteract();
 }
 look(dx,dy){this.yaw-=dx*.0023;this.pitch=THREE.MathUtils.clamp(this.pitch-dy*.0023,-1.35,1.35);}
 start(id){this.position.fromArray(STARTS[id]||STARTS.front);this.eyeY=this.position.y+this.eyeHeight;this.velocityY=0;this.grounded=true;this.yaw=0;this.pitch=0;this.active=true;this.keys.clear();this.canvas.focus({preventScroll:true});this.syncCamera(1);}
 stop(){this.active=false;this.keys.clear();this.touchMove={x:0,z:0};if(document.pointerLockElement)document.exitPointerLock();}
 syncCamera(dt){this.eyeY=THREE.MathUtils.damp(this.eyeY,this.position.y+this.eyeHeight,18,dt);this.camera.position.set(this.position.x,this.eyeY,this.position.z);this.camera.rotation.set(this.pitch,this.yaw,0,'YXZ');}
 update(dt){if(!this.active)return;const canMove=!document.hidden&&!document.querySelector('dialog[open]');let x=0,z=0;if(canMove){x=(this.keys.has('KeyD')||this.keys.has('ArrowRight')?1:0)-(this.keys.has('KeyA')||this.keys.has('ArrowLeft')?1:0)+this.touchMove.x;z=(this.keys.has('KeyS')||this.keys.has('ArrowDown')?1:0)-(this.keys.has('KeyW')||this.keys.has('ArrowUp')?1:0)+this.touchMove.z;}
 const input=new THREE.Vector3(x,0,z);if(input.length()>1)input.normalize();input.applyAxisAngle(new THREE.Vector3(0,1,0),this.yaw).multiplyScalar((this.keys.has('ShiftLeft')?2.7:1.8)*dt);this.world.move(this,input,dt);this.syncCamera(dt);
 }
 currentRoom(){const floor=this.position.y>6.0?2:this.position.y>2.85?1:0;return ROOMS.find(r=>r.floor===floor&&this.position.x>=r.x&&this.position.x<=r.x+r.w&&this.position.z>=r.z&&this.position.z<=r.z+r.d)?.name||(this.position.x>3.2&&this.position.x<4.4&&this.position.z>2.8&&this.position.z<6.5?'Staircase':floor?'Landing':this.position.z>8.1?'Front Entrance':'Hall');}
}
